// 지역별 도시가스 공급사 주택용 요금표.
// 각 공급사 공식 홈페이지(또는 관할 지자체 공공요금 안내) 기준으로 조사한 값이며,
// 도시가스 요금은 격월/수시로 조정되므로 반드시 effectiveDate·source를 함께 확인할 것.
//
// unitPrices.heating이 숫자면 전 구간 동일 단가, { below516, above516 }이면
// 월 516MJ를 기준으로 취사 단가/난방 단가가 갈리는 구간요금제(서울·대전 등)를 의미한다.
export const GAS_REGIONS = {
  seoul: {
    name: '서울',
    provider: '서울도시가스',
    effectiveDate: '2026-07-01',
    baseFee: 1250,
    unitPrices: {
      cooking: 22.3617,
      heating: 22.3617,
    },
    vatIncluded: false,
    source: 'https://www.seoulgas.co.kr/mobile/payment/gasPayTable',
  },
  incheon: {
    name: '인천',
    provider: '삼천리',
    effectiveDate: '2025-08-01',
    baseFee: 1000,
    unitPrices: {
      cooking: 22.5084,
      heating: 22.5084,
    },
    vatIncluded: false,
    source: 'https://www.incheon.go.kr/eco/ECO020806',
    note: '삼천리 공식 페이지 직접 열람이 되지 않아 인천광역시 공공요금 안내 자료(2025-08-01 기준) 값을 사용. 최신 고시 여부는 삼천리 고객센터로 재확인 필요.',
  },
  busan: {
    name: '부산',
    provider: '부산도시가스',
    effectiveDate: '2026-07-01',
    baseFee: 900,
    baseFeeApproximate: true,
    unitPrices: {
      cooking: 23.2186,
      heating: 23.2186,
    },
    vatIncluded: false,
    source: 'https://www.skens.com/busan/rate/guide.do',
    note: '공식 요금표 페이지에는 기본요금이 게시되어 있지 않아 부산광역시 공공요금 안내 자료 기준 근사값 사용. 정확한 금액은 고객센터(1544-0009) 확인 필요.',
  },
  daegu: {
    name: '대구',
    provider: '대성에너지',
    effectiveDate: '2026-07-01',
    baseFee: 900,
    baseFeeApproximate: true,
    unitPrices: {
      cooking: 23.6361,
      heating: 23.6361,
    },
    vatIncluded: false,
    source: 'https://cyber.daesungenergy.com/charge/pricetable',
    note: '공식 요금단가표(2026-07-01 적용)에는 기본요금이 게시되어 있지 않음. 에너지신문 대구시 도시가스 소매공급비용 조정 보도(2025-07-31, https://www.energy-news.co.kr/news/articleView.html?idxno=216275)에 따르면 주택용 기본요금은 취사난방용(개별난방) 900원/월, 취사전용 1,490원/격월(2개월)로 구성되며 해당 조정에서 동결됨. 본 계산기는 개별난방(취사난방용) 기준 900원만 반영하며, 취사 전용으로 검침되는 가구의 격월 청구 기본요금(1,490원/2개월)은 반영하지 못함. 정확한 금액은 고객센터(1577-1190) 확인 필요.',
  },
  gyeongsan: {
    name: '경산',
    provider: '대성에너지',
    effectiveDate: '2026-07-01',
    baseFee: 900,
    baseFeeApproximate: true,
    unitPrices: {
      cooking: 23.6361,
      heating: 23.6361,
    },
    vatIncluded: false,
    source: 'https://cyber.daesungenergy.com/charge/pricetable',
    note: '대성에너지는 대구광역시·경산시 전역·고령군·칠곡군 동명면을 단일 공급권역으로 하는 하나의 공급사이므로 대구와 동일한 요금(기본요금·단가)이 적용됨. 기본요금 근사치의 한계(취사전용 1,490원/격월 미반영)도 대구 항목과 동일. 정확한 금액은 고객센터(1577-1190) 확인 필요.',
  },
  gwangju: {
    name: '광주',
    provider: '해양에너지',
    effectiveDate: '2026-07-01',
    baseFee: 750,
    unitPrices: {
      cooking: 22.0252,
      heating: 23.297,
    },
    vatIncluded: false,
    source: 'https://www.hyenergy.co.kr/charge/pay_notify01.asp',
    note: '부가세 별도/포함 여부가 공식 페이지에 명시되어 있지 않아 업계 관행(별도)으로 가정.',
  },
  daejeon: {
    name: '대전',
    provider: '씨엔씨티에너지',
    effectiveDate: '2026-07-01',
    baseFee: 850,
    unitPrices: {
      cooking: 23.2332,
      heating: { below516: 23.2332, above516: 24.074 },
    },
    vatIncluded: false,
    source: 'https://www.cncityenergy.com/jsp/customer/chargeInfoGas.jsp?menuId=882',
  },
  ulsan: {
    name: '울산',
    provider: '경동도시가스',
    effectiveDate: '2026-06-01',
    baseFee: 778,
    unitPrices: {
      cooking: 22.818,
      heating: 22.818,
    },
    vatIncluded: false,
    source: 'http://www.citygas.or.kr/info/charge.jsp',
    note: '한국도시가스협회 공식 요금표(2026-06-01 조정분) 기준. 경동도시가스 자체 홈페이지에서 동일 수치를 직접 재확인하지 못해 협회 취합 자료를 사용했으며, 정확한 금액은 고객센터(1577-8181)로 재확인 권장.',
  },
  gyeonggi: {
    name: '경기도',
    provider: '삼천리 외',
    effectiveDate: '2026-06-01',
    baseFee: 1250,
    unitPrices: {
      cooking: 22.6226,
      heating: 22.6226,
    },
    vatIncluded: false,
    source: 'http://www.citygas.or.kr/info/charge.jsp',
    note: '경기도 내 다수 지역(수원·부천·평택·안양 등, 삼천리 관할)을 포함한 대표값. 경기도는 공급사(삼천리·코원에너지서비스·예스코·대륜이엔에스 등)와 무관하게 도 전체에 동일한 소매요금이 적용됨을 다수 공급사 공식 요금조회 결과로 교차 확인함(2026-07-06 확인, 상세는 "성남"·"남양주"·"의정부"·"용인" 등 지역 항목 참고).',
  },
  yongin: {
    name: '용인(경기)',
    provider: '삼천리',
    effectiveDate: '2026-06-01',
    baseFee: 1250,
    unitPrices: {
      cooking: 22.6226,
      heating: 22.6226,
    },
    vatIncluded: false,
    source: 'https://www.kogas.or.kr/site/koGas/1020408040000',
    note: '한국가스공사 공식 공급구역 안내(2026-07-10 확인) 기준 삼천리㈜ 공급권역(부천·시흥·안산·안양·광명·의왕·군포·수원·화성·용인·안성·평택·오산시). 이미 "경기도" 항목의 근거인 삼천리 관할에 포함되는 지역이라 별도 자체 요금조회 없이 동일 수치를 적용.',
  },
  hwaseong: {
    name: '화성(경기)',
    provider: '삼천리',
    effectiveDate: '2026-06-01',
    baseFee: 1250,
    unitPrices: {
      cooking: 22.6226,
      heating: 22.6226,
    },
    vatIncluded: false,
    source: 'https://www.kogas.or.kr/site/koGas/1020408040000',
    note: '한국가스공사 공식 공급구역 안내(2026-07-10 확인) 기준 삼천리㈜ 공급권역(부천·시흥·안산·안양·광명·의왕·군포·수원·화성·용인·안성·평택·오산시). 이미 "경기도" 항목의 근거인 삼천리 관할에 포함되는 지역이라 별도 자체 요금조회 없이 동일 수치를 적용.',
  },
  ansan: {
    name: '안산(경기)',
    provider: '삼천리',
    effectiveDate: '2026-06-01',
    baseFee: 1250,
    unitPrices: {
      cooking: 22.6226,
      heating: 22.6226,
    },
    vatIncluded: false,
    source: 'https://www.kogas.or.kr/site/koGas/1020408040000',
    note: '한국가스공사 공식 공급구역 안내(2026-07-10 확인) 기준 삼천리㈜ 공급권역(부천·시흥·안산·안양·광명·의왕·군포·수원·화성·용인·안성·평택·오산시). 이미 "경기도" 항목의 근거인 삼천리 관할에 포함되는 지역이라 별도 자체 요금조회 없이 동일 수치를 적용.',
  },
  siheung: {
    name: '시흥(경기)',
    provider: '삼천리',
    effectiveDate: '2026-06-01',
    baseFee: 1250,
    unitPrices: {
      cooking: 22.6226,
      heating: 22.6226,
    },
    vatIncluded: false,
    source: 'https://www.kogas.or.kr/site/koGas/1020408040000',
    note: '한국가스공사 공식 공급구역 안내(2026-07-10 확인) 기준 삼천리㈜ 공급권역(부천·시흥·안산·안양·광명·의왕·군포·수원·화성·용인·안성·평택·오산시). 이미 "경기도" 항목의 근거인 삼천리 관할에 포함되는 지역이라 별도 자체 요금조회 없이 동일 수치를 적용.',
  },
  seongnam: {
    name: '성남(경기)',
    provider: '코원에너지서비스',
    effectiveDate: '2026-07-01',
    baseFee: 1250,
    unitPrices: {
      cooking: 22.6226,
      heating: 22.6226,
    },
    vatIncluded: false,
    source: 'https://www.skens.com/koone/rate/guide.do',
    note: '코원에너지서비스㈜ 공급권역(과천·성남·하남·광주·이천·여주시 등, 한국가스공사 공식 공급구역 안내 https://www.kogas.or.kr/site/koGas/1020408040000 기준) 자체 요금조회 페이지에서 직접 확인. "경기도" 항목(삼천리 기준)과 수치가 동일해, 경기도는 공급사와 무관하게 도 전체 동일 소매요금이 적용됨을 확인함.',
  },
  namyangju: {
    name: '남양주(경기)',
    provider: '예스코',
    effectiveDate: '2025-08-01',
    baseFee: 1250,
    unitPrices: {
      cooking: 22.6226,
      heating: 22.6226,
    },
    vatIncluded: false,
    source: 'https://www.lsyesco.com/CustGuide/gasCostManage.view',
    note: '예스코 공급권역(구리·남양주시·가평군, 한국가스공사 공식 공급구역 안내 https://www.kogas.or.kr/site/koGas/1020408040000 기준) 요금조회 페이지는 화면이 스크립트로 렌더링되어 페이지 내부 API 응답을 직접 조회해 확인(2026-07-06). "경기도" 항목(삼천리 기준)과 수치가 동일함.',
  },
  gyeongnam: {
    name: '경남',
    provider: '경남에너지',
    effectiveDate: '2026-06-01',
    baseFee: 850,
    baseFeeApproximate: true,
    unitPrices: {
      cooking: 24.2101,
      heating: 24.2101,
    },
    vatIncluded: false,
    source: 'http://www.citygas.or.kr/info/charge.jsp',
    note: '경남에너지 공급권역(창원·통영·김해·밀양·거제·의령·함안·창녕·고성) 대표값. 기본요금은 개별난방 기준 850원이며, 취사전용 요금제는 기본요금이 1,700원으로 더 높음(경남에너지 공식 홈페이지 www.knenergy.co.kr 요금안내에서 교차 확인). 진주(지에스이)·양산(경동도시가스) 등 경남 내 타 지역은 공급사가 달라 요금이 다름.',
  },
  sejong: {
    name: '세종',
    provider: '중부도시가스',
    effectiveDate: '2026-06-01',
    baseFee: 820,
    baseFeeApproximate: true,
    unitPrices: {
      cooking: 22.2887,
      heating: 24.4433,
    },
    vatIncluded: false,
    source: 'http://www.citygas.or.kr/info/charge.jsp',
    note: '한국도시가스협회 공식 요금표(2026-06-01 조정분) 기준. 기본요금은 개별난방·중앙난방 공용 요금(820원)이며, 취사전용 요금제는 기본요금이 2,533원으로 더 높음. 중부도시가스 자체 홈페이지에서 요금표 페이지를 직접 확인하지 못해 협회 취합 자료를 사용했으며, 정확한 금액은 고객센터(1544-0041)로 재확인 권장.',
  },
  gangwon: {
    name: '강원(춘천 등)',
    provider: '강원도시가스',
    effectiveDate: '2026-07-01',
    baseFee: 1150,
    unitPrices: {
      cooking: 24.1221,
      heating: 24.1221,
    },
    vatIncluded: false,
    source: 'https://www.skens.com/gangwon/rate/guide.do',
    note: '강원도시가스 공급권역(춘천·홍천·영월·정선·태백) 대표값. 강원 영동지역(강릉·동해·삼척은 참빛영동도시가스, 속초·고성·양양은 참빛도시가스 관할)은 요금이 달라 "강릉"·"속초" 지역을 별도로 선택할 수 있음.',
  },
  gangneung: {
    name: '강릉(강원 영동)',
    provider: '참빛영동도시가스',
    effectiveDate: '2026-06-01',
    baseFee: 1150,
    unitPrices: {
      cooking: 25.0337,
      heating: 25.0337,
    },
    vatIncluded: false,
    source: 'http://www.citygas.or.kr/info/charge.jsp',
    note: '참빛영동도시가스㈜ 공급권역(강릉·동해·삼척, 한국가스공사 공식 공급구역 안내 https://www.kogas.or.kr/site/koGas/1020408040000 기준). 한국도시가스협회 공식 요금표(2026-06-01 조정분)에는 인접한 속초 지역(참빛도시가스㈜ 관할)과 "강원 영동지역"으로 합산 표기되어 있어 동일 수치를 사용. 정확한 금액은 고객센터(1899-9100)로 재확인 권장.',
  },
  sokcho: {
    name: '속초(강원 영동)',
    provider: '참빛도시가스',
    effectiveDate: '2026-06-01',
    baseFee: 1150,
    unitPrices: {
      cooking: 25.0337,
      heating: 25.0337,
    },
    vatIncluded: false,
    source: 'http://www.citygas.or.kr/info/charge.jsp',
    note: '참빛도시가스㈜ 공급권역(속초·고성·양양, 한국가스공사 공식 공급구역 안내 https://www.kogas.or.kr/site/koGas/1020408040000 기준). 한국도시가스협회 공식 요금표(2026-06-01 조정분)에는 인접한 강릉 지역(참빛영동도시가스㈜ 관할)과 "강원 영동지역"으로 합산 표기되어 있어 동일 수치를 사용. 정확한 금액은 고객센터(1899-9100)로 재확인 권장.',
  },
  cheongju: {
    name: '청주',
    provider: '충청에너지서비스',
    effectiveDate: '2026-07-01',
    baseFee: 1050,
    unitPrices: {
      cooking: 23.4509,
      heating: 23.2208,
    },
    vatIncluded: false,
    source: 'https://www.skens.com/cheongju/rate/guide.do',
    note: '충청에너지서비스 공식 홈페이지 요금안내 페이지에서 직접 확인(2026-07-01 적용).',
  },
  cheonan: {
    name: '천안',
    provider: '중부도시가스',
    effectiveDate: '2026-06-01',
    baseFee: 1000,
    unitPrices: {
      cooking: 24.1111,
      heating: 24.1111,
    },
    vatIncluded: false,
    source: 'http://www.citygas.or.kr/info/charge.jsp',
    note: '한국도시가스협회 공식 요금표(2026-06-01 조정분) 기준. 중부도시가스 자체 홈페이지 요금표 페이지 접근이 되지 않아 협회 취합 자료를 사용했으며, 정확한 금액은 고객센터(1544-0041)로 재확인 권장. 아산·공주·보령 등 중부도시가스 공급권역 내 타 지역도 유사하나 정확한 수치는 별도 확인 필요.',
  },
  asan: {
    name: '아산',
    provider: '중부도시가스',
    effectiveDate: '2026-06-01',
    baseFee: 1000,
    baseFeeApproximate: true,
    unitPrices: {
      cooking: 24.1111,
      heating: 24.1111,
    },
    vatIncluded: false,
    source: 'http://www.citygas.or.kr/info/charge.jsp',
    note: '중부도시가스 공급권역(천안·아산·공주·보령 등 충남 일대)이나, 한국도시가스협회 공식 요금표(2026-06-01 조정분)에는 "충남 천안시(JB)" 대표값 하나로만 취합되어 아산 개별 수치가 공시되지 않음. 중부도시가스 자체 홈페이지에서도 아산 지역 요금표 페이지를 확인하지 못해, 천안과 동일한 대표값을 근사치로 사용. 정확한 금액은 고객센터(1544-0041)로 재확인 권장.',
  },
  gongju: {
    name: '공주',
    provider: '중부도시가스',
    effectiveDate: '2026-06-01',
    baseFee: 1000,
    baseFeeApproximate: true,
    unitPrices: {
      cooking: 24.1111,
      heating: 24.1111,
    },
    vatIncluded: false,
    source: 'http://www.citygas.or.kr/info/charge.jsp',
    note: '중부도시가스 공급권역(천안·아산·공주·보령 등 충남 일대)이나, 한국도시가스협회 공식 요금표(2026-06-01 조정분)에는 "충남 천안시(JB)" 대표값 하나로만 취합되어 공주 개별 수치가 공시되지 않음. 중부도시가스 자체 홈페이지에서도 공주 지역 요금표 페이지를 확인하지 못해, 천안과 동일한 대표값을 근사치로 사용. 정확한 금액은 고객센터(1544-0041)로 재확인 권장.',
  },
  boryeong: {
    name: '보령',
    provider: '중부도시가스',
    effectiveDate: '2026-06-01',
    baseFee: 1000,
    baseFeeApproximate: true,
    unitPrices: {
      cooking: 24.1111,
      heating: 24.1111,
    },
    vatIncluded: false,
    source: 'http://www.citygas.or.kr/info/charge.jsp',
    note: '중부도시가스 공급권역(천안·아산·공주·보령 등 충남 일대)이나, 한국도시가스협회 공식 요금표(2026-06-01 조정분)에는 "충남 천안시(JB)" 대표값 하나로만 취합되어 보령 개별 수치가 공시되지 않음. 중부도시가스 자체 홈페이지에서도 보령 지역 요금표 페이지를 확인하지 못해, 천안과 동일한 대표값을 근사치로 사용. 정확한 금액은 고객센터(1544-0041)로 재확인 권장.',
  },
  jeonju: {
    name: '전주',
    provider: '전북도시가스',
    effectiveDate: '2026-06-01',
    baseFee: 900,
    unitPrices: {
      cooking: 23.0303,
      heating: 23.0303,
    },
    vatIncluded: false,
    source: 'http://www.citygas.or.kr/info/charge.jsp',
    note: '전북도시가스㈜ 공급권역(전주 등). 한국도시가스협회 공식 요금표(2026-06-01 조정분) 기준. 익산(전북에너지서비스)·군산(군산도시가스)은 공급사가 달라 요금이 다름.',
  },
  gunsan: {
    name: '군산',
    provider: '군산도시가스',
    effectiveDate: '2026-07-01',
    baseFee: 900,
    unitPrices: {
      cooking: 23.6869,
      heating: 23.6869,
    },
    vatIncluded: false,
    source: 'http://www.kscg.co.kr/pay_manage/pay_info.do',
    note: '군산도시가스㈜ 공급권역(군산·임실·부안 등) 자체 홈페이지 게시 요금단가표(PDF, 2026-07-01 적용)에서 직접 확인. 한국도시가스협회 공식 요금표(2026-06-01 조정분)에도 동일 수치(기본요금 900원, 23.6869원/MJ)로 게재되어 있어 교차 확인함. 전주(전북도시가스)·익산(전북에너지서비스)은 공급사가 달라 요금이 다름.',
  },
  iksan: {
    name: '익산',
    provider: '전북에너지서비스',
    effectiveDate: '2026-07-01',
    baseFee: 900,
    baseFeeApproximate: true,
    unitPrices: {
      cooking: 24.5417,
      heating: 24.5417,
    },
    vatIncluded: false,
    source: 'https://www.skens.com/jeonbuk/rate/guide.do',
    note: '전북에너지서비스㈜ 공급권역(익산·정읍) 자체 홈페이지 요금안내 페이지에서 직접 확인(2026-07-01 적용). 기본요금은 개별난방/일반 주택용 기준 900원이며, 지역난방(집단에너지) 요금제는 기본요금이 1,465원으로 더 높음. 단가(24.5417원/MJ)는 한국도시가스협회 공식 요금표(2026-06-01 조정분)와도 일치. 전주(전북도시가스)·군산(군산도시가스)은 공급사가 달라 요금이 다름.',
  },
  pohang: {
    name: '포항',
    provider: '영남에너지서비스',
    effectiveDate: '2026-06-01',
    baseFee: 750,
    unitPrices: {
      cooking: 23.5198,
      heating: 23.5198,
    },
    vatIncluded: false,
    source: 'http://www.citygas.or.kr/info/charge.jsp',
    note: '영남에너지서비스㈜(포항) 공급권역. 한국도시가스협회 공식 요금표(2026-06-01 조정분) 기준. 같은 영남에너지서비스라도 구미 사업장은 별도 법인(영남에너지서비스㈜(구미))으로 요금이 달라 별도 항목으로 분리(아래 "구미" 참고).',
  },
  gumi: {
    name: '구미',
    provider: '영남에너지서비스(구미)',
    effectiveDate: '2026-07-01',
    baseFee: 750,
    unitPrices: {
      cooking: 23.6062,
      heating: 23.6062,
    },
    vatIncluded: false,
    source: 'https://www.skens.com/gumi/rate/guide.do',
    note: '영남에너지서비스㈜(구미) 공급권역(구미·김천·상주·문경시 등, 한국가스공사 공식 공급구역 안내 https://www.kogas.or.kr/site/koGas/1020408040000 기준). 포항 사업장과 법인이 달라 요금도 다름(자체 홈페이지, 2026-07-01 적용). 한국도시가스협회 공식 요금표(2026-06-01 조정분)와도 수치가 일치(기본요금 750원, 23.6062원/MJ).',
  },
  gyeongju: {
    name: '경주',
    provider: '서라벌도시가스',
    effectiveDate: '2026-06-01',
    baseFee: 750,
    unitPrices: {
      cooking: 23.3923,
      heating: 23.3923,
    },
    vatIncluded: false,
    source: 'http://www.citygas.or.kr/info/charge.jsp',
    note: '서라벌도시가스㈜ 공급권역(경주·영천시, 한국가스공사 공식 공급구역 안내 https://www.kogas.or.kr/site/koGas/1020408040000 기준). 자체 홈페이지(srbgas.co.kr) 접근이 차단(403)되어 한국도시가스협회 공식 요금표(2026-06-01 조정분)를 사용. 정확한 금액은 고객센터(1544-5916)로 재확인 권장.',
  },
  andong: {
    name: '안동',
    provider: '대성청정에너지',
    effectiveDate: '2026-07-01',
    baseFee: 750,
    baseFeeApproximate: true,
    unitPrices: {
      cooking: 24.3795,
      heating: 24.3795,
    },
    vatIncluded: false,
    source: 'http://www.daesungcleanenergy.co.kr/charge/pricetable',
    note: '대성청정에너지㈜ 공급권역(안동·영주시, 예천·봉화·의성·군위군 등, 한국가스공사 공식 공급구역 안내 https://www.kogas.or.kr/site/koGas/1020408040000 기준). 단가(24.3795원/MJ)는 자체 홈페이지 요금단가표에서 직접 확인(2026-07-01 적용)했으나 기본요금은 공식 페이지에 게시되어 있지 않아 한국도시가스협회 공식 요금표(2026-06-01 조정분, 동일 단가 확인됨)의 750원을 사용. 정확한 금액은 고객센터로 재확인 권장.',
  },
  jinju: {
    name: '진주',
    provider: '지에스이',
    effectiveDate: '2026-07-01',
    baseFee: 1100,
    baseFeeApproximate: true,
    unitPrices: {
      cooking: 24.7753,
      heating: 24.7753,
    },
    vatIncluded: false,
    source: 'https://www.yesgse.com/user/pay.info.unitcost.asp',
    note: '㈜지에스이 공급권역(진주 등) 공식 홈페이지에서 직접 확인(2026-07-01 기준). 기본요금은 취사전용·개별난방 1,100원이며, 취사전용(지역난방/집단에너지) 요금제는 1,700원으로 더 높음. 한국도시가스협회 공식 요금표(2026-06-01 조정분)의 수치와도 일치.',
  },
  yeosu: {
    name: '여수',
    provider: '대화도시가스',
    effectiveDate: '2026-06-01',
    baseFee: 870,
    unitPrices: {
      cooking: 22.9782,
      heating: 22.9782,
    },
    vatIncluded: false,
    source: 'http://www.citygas.or.kr/info/charge.jsp',
    note: '대화도시가스㈜ 공급권역(여수 등). 한국도시가스협회 공식 요금표(2026-06-01 조정분) 기준.',
  },
  suncheon: {
    name: '순천',
    provider: '전남도시가스',
    effectiveDate: '2026-06-01',
    baseFee: 870,
    unitPrices: {
      cooking: 23.9772,
      heating: 23.9772,
    },
    vatIncluded: false,
    source: 'http://www.citygas.or.kr/info/charge.jsp',
    note: '전남도시가스㈜ 공급권역(순천 등). 한국도시가스협회 공식 요금표(2026-06-01 조정분) 기준.',
  },
  mokpo: {
    name: '목포',
    provider: 'MC에너지',
    effectiveDate: '2026-06-01',
    baseFee: 870,
    unitPrices: {
      cooking: 23.9447,
      heating: 23.9447,
    },
    vatIncluded: false,
    source: 'http://www.citygas.or.kr/info/charge.jsp',
    note: 'MC에너지(옛 목포도시가스) 공급권역(목포 등). 한국도시가스협회 공식 요금표(2026-06-01 조정분) 기준.',
  },
  yangsan: {
    name: '양산',
    provider: '경동도시가스',
    effectiveDate: '2026-06-01',
    baseFee: 850,
    baseFeeApproximate: true,
    unitPrices: {
      cooking: 23.9659,
      heating: 23.9659,
    },
    vatIncluded: false,
    source: 'http://www.citygas.or.kr/info/charge.jsp',
    note: '경동도시가스㈜의 경남 양산 사업장 공급권역. 기본요금은 취사전용·개별난방 850원이며, 지역난방(집단에너지) 요금제는 1,700원으로 더 높음. 울산 사업장과 같은 회사이나 요금은 지역별로 달라 별도 항목으로 분리(한국도시가스협회 공식 요금표, 2026-06-01 조정분 기준).',
  },
  uijeongbu: {
    name: '의정부(경기 북부)',
    provider: '대륜이엔에스',
    effectiveDate: '2026-07-01',
    baseFee: 1250,
    unitPrices: {
      cooking: 22.6226,
      heating: 22.6226,
    },
    vatIncluded: false,
    source: 'http://www.daeryunens.com/daeryunens/bbs/bbs_list.asp?bbs_code=54',
    note: '㈜대륜이엔에스 공급권역(의정부·양주·동두천시, 연천군, 포천시 일부 및 서울 노원·도봉·강북구 일부, 한국가스공사 공식 공급구역 안내 https://www.kogas.or.kr/site/koGas/1020408040000 기준). 5차 확장 세션에서는 자체 요금조회 페이지가 로그인 장벽으로 막혀 제외했으나, 이번에는 회사 게시판("가스 요금표 및 경제성 비교")에 첨부된 공식 PDF "도시가스 단가표 / 2026. 7. 1."에서 직접 확인. 대륜이엔에스는 서울 권역엔 "서울" 요금, 경기(의정부 등) 권역엔 "경기" 요금(기본요금 1,250원, 22.6226원/MJ)을 적용하며, 이는 기존 "경기도" 항목(삼천리 기준)과 동일 — 경기도는 공급사와 무관하게 도 전체 동일 소매요금이 적용됨을 재확인.',
  },
  wonju: {
    name: '원주(강원)',
    provider: '참빛원주도시가스',
    effectiveDate: '2026-07-01',
    baseFee: 1150,
    unitPrices: {
      cooking: 23.4348,
      heating: 23.4348,
    },
    vatIncluded: false,
    source: 'http://www.cwjgas.co.kr/charge/charge01.do',
    note: '참빛원주도시가스㈜ 공급권역(원주시·횡성군, 한국가스공사 공식 공급구역 안내 https://www.kogas.or.kr/site/koGas/1020408040000 기준) 자체 홈페이지 요금안내 페이지에서 직접 확인("적용일자 : 2026-07-01 기준" 명시). 한국도시가스협회 공식 요금표(2026-06-01 조정분)와도 수치 일치(기본요금 1,150원, 23.4348원/MJ). 기존 "강원(춘천 등)" 지역(강원도시가스 관할)과는 공급사가 달라 요금이 다름.',
  },
  hoengseong: {
    name: '횡성(강원)',
    provider: '참빛원주도시가스',
    effectiveDate: '2026-07-01',
    baseFee: 1150,
    unitPrices: {
      cooking: 23.4348,
      heating: 23.4348,
    },
    vatIncluded: false,
    source: 'http://www.cwjgas.co.kr/charge/charge01.do',
    note: '참빛원주도시가스㈜ 공급권역(원주시·횡성군, 자체 홈페이지 공급권역 안내 http://www.cwjgas.co.kr/introduction/intro03.do 및 한국가스공사 공식 공급구역 안내 https://www.kogas.or.kr/site/koGas/1020408040000 기준)이 원주와 동일하여 원주 지역과 완전히 동일한 요금이 적용됨. 확인일 2026-07-08(자체 홈페이지 요금안내 페이지 "적용일자 : 2026-07-01 기준" 재확인, 기본요금 1,150원/월, 23.4348원/MJ 변동 없음).',
  },
  pyeongchang: {
    name: '평창(강원)',
    provider: '명성파워그린',
    effectiveDate: '2026-06-01',
    baseFee: 1150,
    unitPrices: {
      cooking: 24.6592,
      heating: 24.6592,
    },
    vatIncluded: false,
    source: 'http://www.citygas.or.kr/info/charge.jsp',
    note: '명성파워그린㈜ 공급권역(평창군, 한국가스공사 공식 공급구역 안내 https://www.kogas.or.kr/site/koGas/1020408040000 기준). 한국도시가스협회 공식 요금표(2026-06-01 조정분)에 "평창(명성)"으로 개별 게재된 수치를 사용(강릉·속초처럼 인근 지역과 합산 표기되지 않은 단독 항목). 자체 홈페이지(myungsungpower.com)에는 요금표 페이지가 게시되어 있지 않아 직접 교차 확인은 하지 못함. 정확한 금액은 고객센터(033-332-6430)로 재확인 권장. 원주·횡성(참빛원주도시가스)과는 공급사가 달라 요금이 다름.',
  },
  chungju: {
    name: '충주',
    provider: '참빛충북도시가스',
    effectiveDate: '2026-07-01',
    baseFee: 1050,
    unitPrices: {
      cooking: 23.8443,
      heating: 23.5906,
    },
    vatIncluded: false,
    source: 'http://www.ccbgas.co.kr/charge/charge01.do',
    note: '참빛충북도시가스㈜ 공급권역(충주시, 한국가스공사 공식 공급구역 안내 https://www.kogas.or.kr/site/koGas/1020408040000 기준) 자체 홈페이지 요금안내 페이지에서 직접 확인("적용일자 : 2026-07-01 기준" 명시, 취사용 23.8443원/MJ과 개별난방 23.5906원/MJ 단가가 서로 다름). 한국도시가스협회 공식 요금표(2026-06-01 조정분)와도 수치 일치. 기존 "청주" 지역(충청에너지서비스 관할)과는 공급사가 달라 요금이 다름.',
  },
  seosan: {
    name: '서산(당진 포함)',
    provider: '미래엔서해에너지',
    effectiveDate: '2026-06-01',
    baseFee: 1000,
    unitPrices: {
      cooking: 24.0552,
      heating: 24.0552,
    },
    vatIncluded: false,
    source: 'http://www.citygas.or.kr/info/charge.jsp',
    note: '미래엔서해에너지㈜ 공급권역(당진·서산시, 홍성·예산·태안군, 한국가스공사 공식 공급구역 안내 https://www.kogas.or.kr/site/koGas/1020408040000 기준). 자체 홈페이지(shgas.co.kr)의 요금정보 페이지가 이미지/스크립트 기반이라 개별 단가를 직접 확인하지 못해 한국도시가스협회 공식 요금표(2026-06-01 조정분)를 사용. 당진시도 동일 공급사·동일 요금이 적용됨. 정확한 금액은 고객센터(1577-6580)로 재확인 권장.',
  },
  jeju: {
    name: '제주',
    provider: '제주도시가스',
    effectiveDate: '2026-06-01',
    baseFee: 1000,
    unitPrices: {
      cooking: 27.0619,
      heating: 27.0619,
    },
    vatIncluded: false,
    source: 'http://www.citygas.or.kr/info/charge.jsp',
    note: '㈜제주도시가스 공급권역(제주·서귀포시, 한국가스공사 공식 공급구역 안내 https://www.kogas.or.kr/site/koGas/1020408040000 기준). 자체 홈페이지가 위지(Wix) 기반 동적 사이트라 요금표를 직접 확인하지 못해 한국도시가스협회 공식 요금표(2026-06-01 조정분)를 사용(기본요금은 개별난방 기준 1,000원이며, 일반용은 2,400원으로 더 높음). 정확한 금액은 고객센터(1600-3437)로 재확인 권장.',
  },
}

export const GAS_REGION_ORDER = [
  'seoul',
  'incheon',
  'busan',
  'daegu',
  'gyeongsan',
  'gwangju',
  'daejeon',
  'ulsan',
  'gyeonggi',
  'yongin',
  'hwaseong',
  'ansan',
  'siheung',
  'seongnam',
  'namyangju',
  'uijeongbu',
  'gyeongnam',
  'jinju',
  'yangsan',
  'sejong',
  'gangwon',
  'gangneung',
  'sokcho',
  'wonju',
  'hoengseong',
  'pyeongchang',
  'cheongju',
  'chungju',
  'cheonan',
  'asan',
  'gongju',
  'boryeong',
  'seosan',
  'jeonju',
  'gunsan',
  'iksan',
  'pohang',
  'gumi',
  'gyeongju',
  'andong',
  'yeosu',
  'suncheon',
  'mokpo',
  'jeju',
]

export const NATIONWIDE_AVERAGE_REGION_ID = 'nationwide-average'

function average(values) {
  return values.reduce((sum, value) => sum + value, 0) / values.length
}

function toFlatUnitPrice(heating) {
  return typeof heating === 'number' ? heating : heating.below516
}

// 미지원 지역용 근사치. 조사 완료된 44개 지역의 단순 평균으로 산출하며,
// 실제 거주 지역 도시가스사 요금표와 차이가 있을 수 있음을 계산기 UI에서 안내한다.
export function getNationwideAverageRegion() {
  const regions = GAS_REGION_ORDER.map((id) => GAS_REGIONS[id])

  return {
    name: '전국 평균(근사치)',
    provider: '미지원 지역 - 전국 평균 근사치',
    effectiveDate: null,
    baseFee: Math.round(average(regions.map((region) => region.baseFee))),
    baseFeeApproximate: true,
    unitPrices: {
      cooking: average(regions.map((region) => region.unitPrices.cooking)),
      heating: average(regions.map((region) => toFlatUnitPrice(region.unitPrices.heating))),
    },
    vatIncluded: false,
    source: null,
    note: '아직 지원하지 않는 지역이라 조사 완료된 44개 지역(서울·인천·부산·대구·경산·광주·대전·울산·경기·용인·화성·안산·시흥·성남·남양주·의정부·경남·진주·양산·세종·강원·강릉·속초·원주·횡성·평창·청주·충주·천안·아산·공주·보령·서산·전주·군산·익산·포항·구미·경주·안동·여수·순천·목포·제주) 요금의 단순 평균으로 근사 계산한 값입니다. 실제 거주 지역 도시가스사 요금표를 확인하세요.',
    isApproximate: true,
  }
}

export function getGasRegion(regionId) {
  if (regionId === NATIONWIDE_AVERAGE_REGION_ID) {
    return getNationwideAverageRegion()
  }

  return GAS_REGIONS[regionId] ?? null
}

export function getGasRegionOptions() {
  return [
    ...GAS_REGION_ORDER.map((id) => ({ id, name: GAS_REGIONS[id].name })),
    { id: NATIONWIDE_AVERAGE_REGION_ID, name: '기타 지역(전국 평균 근사치)' },
  ]
}
